import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="mx-auto flex min-h-screen max-w-5xl flex-col px-4 py-8">
          {" "}
          <header className="mb-8">
            <h1 className="text-3xl font-semibold tracking-tight">
              Serverless Real-Time Voting Demo
            </h1>
            <p className="mt-2 max-w-2xl text-sm text-slate-400">
              Votes flow from this UI through Next.js → API Gateway → Kinesis →
              Lambda → DynamoDB. Results are read back and displayed live.
            </p>
          </header>
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
